# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

revcompR <- function(sequences) {
    .Call(`_jaeger_revcompR`, sequences)
}

check_whitelist <- function(r_whitelist_df, mutations) {
    .Call(`_jaeger_check_whitelist`, r_whitelist_df, mutations)
}

barcodes_to_bits <- function(barcodes) {
    .Call(`_jaeger_barcodes_to_bits`, barcodes)
}

bits_to_barcodes <- function(input, barcode_length = 16L, verbose = FALSE) {
    .Call(`_jaeger_bits_to_barcodes`, input, barcode_length, verbose)
}

mutate_and_check <- function(barcode, max_mutations, r_whitelist_df, barcode_length = 16L) {
    .Call(`_jaeger_mutate_and_check`, barcode, max_mutations, r_whitelist_df, barcode_length)
}

baj_extract <- function(sigstrings, whitelist_df, df, nthreads, verbose = FALSE, max_iterations = 4L, max_mutations = 4L, barcode_length = 16L, barcorrect = FALSE, jaccard_on = TRUE) {
    .Call(`_jaeger_baj_extract`, sigstrings, whitelist_df, df, nthreads, verbose, max_iterations, max_mutations, barcode_length, barcorrect, jaccard_on)
}

bajalign_sigs <- function(adapters, sequences, null_distance, nthreads) {
    .Call(`_jaeger_bajalign_sigs`, adapters, sequences, null_distance, nthreads)
}

bajalign_stats <- function(adapters, sequences, nthreads = 1L) {
    .Call(`_jaeger_bajalign_stats`, adapters, sequences, nthreads)
}

bajbatch <- function(null_distance, read_layout, sigstrings, verbose = FALSE) {
    .Call(`_jaeger_bajbatch`, null_distance, read_layout, sigstrings, verbose)
}

rcpp_hello_world <- function() {
    .Call(`_jaeger_rcpp_hello_world`)
}

